import { Permission, Role } from 'appwrite';
import { databases } from '@/lib/appwrite';
import { FormField, FormConfig } from '@/lib/types';
import { logAction } from './audit-service';

const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
const FORM_CONFIG_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_FORM_CONFIG_COLLECTION_ID!;

// Singleton document ID for form configuration
const FORM_CONFIG_DOC_ID = 'current';
const CLOSURE_FORM_CONFIG_DOC_ID = 'closure';
const PAYMENT_PLAN_FORM_CONFIG_DOC_ID = 'payment_plan';
const CLIENT_INTAKE_FORM_CONFIG_DOC_ID = 'client_intake';

/**
 * Default form fields configuration
 * These fields are used when no custom configuration exists.
 *
 * Field keys are uniform across all leads generated by any user type. Earlier
 * versions of the form config used generic auto-generated keys (e.g.
 * `field_15` for Amount, `field_16` for LinkedIn Profile URL). New leads
 * are stored under the uniform keys below; legacy data is read via alias
 * maps in `lib/utils/lead-linkedin-field.ts` and
 * `app/leads/[id]/page.tsx` so historical leads still render correctly.
 */
export const DEFAULT_FIELDS: FormField[] = [
  { id: '1', type: 'text', label: 'First Name', key: 'firstName', required: true, visible: true, order: 1 },
  { id: '2', type: 'text', label: 'Last Name', key: 'lastName', required: true, visible: true, order: 2 },
  { id: '3', type: 'email', label: 'Email', key: 'email', required: true, visible: true, order: 3 },
  { id: '4', type: 'phone', label: 'Phone', key: 'phone', required: false, visible: true, order: 4 },
  { id: '5', type: 'text', label: 'Company', key: 'company', required: false, visible: true, order: 5 },
  {
    id: '6',
    type: 'dropdown',
    label: 'Source',
    key: 'source',
    required: false,
    visible: true,
    order: 6,
    options: ['Website', 'Referral', 'Cold Call', 'Social Media'],
  },
  {
    id: '7',
    type: 'dropdown',
    label: 'Status',
    key: 'status',
    required: true,
    visible: true,
    order: 7,
    options: ['Interested', 'Not Interested', 'Pipeline', 'Prospect', 'Signed'],
  },
  { id: '8', type: 'text', label: 'Legal Name', key: 'legalName', required: true, visible: true, order: 8 },
  {
    id: '9',
    type: 'text',
    label: 'SSN (Last 4)',
    key: 'ssnLast4',
    required: false,
    visible: true,
    order: 9,
    validation: { pattern: '^\\d{4}$', minLength: 4, maxLength: 4 },
  },
  {
    id: '10',
    type: 'dropdown',
    label: 'Visa Status',
    key: 'visaStatus',
    required: false,
    visible: true,
    order: 10,
    options: ['Citizen', 'Green Card', 'H1B', 'F1', 'Other'],
  },
  { id: '11', type: 'textarea', label: 'Notes', key: 'notes', required: false, visible: true, order: 11 },
  {
    id: '12',
    type: 'text',
    label: 'Amount ($)',
    key: 'amount',
    required: true,
    visible: true,
    order: 12,
    validation: { pattern: '^\\d+(\\.\\d{1,2})?$' },
  },
  {
    id: '13',
    type: 'text',
    label: 'LinkedIn Profile URL',
    key: 'linkedinProfileUrl',
    required: true,
    visible: true,
    order: 13,
  },
];

export const DEFAULT_CLOSURE_FIELDS: FormField[] = [
  { id: '1', type: 'text', label: 'First Name', key: 'firstName', required: true, visible: true, order: 1 },
  { id: '2', type: 'text', label: 'Last Name', key: 'lastName', required: false, visible: true, order: 2 },
  { id: '3', type: 'email', label: 'Email', key: 'email', required: true, visible: true, order: 3 },
  { id: '4', type: 'phone', label: 'Phone', key: 'phone', required: false, visible: true, order: 4 },
  { id: '5', type: 'text', label: 'Address', key: 'address', required: false, visible: true, order: 5 },
];

export const DEFAULT_PAYMENT_PLAN_FIELDS: FormField[] = [
  {
    id: '1',
    type: 'dropdown',
    label: 'Payment Percentage',
    key: 'paymentPercent',
    required: true,
    visible: true,
    order: 1,
    options: ['10', '11', '12', '14'],
  },
  {
    id: '2',
    type: 'dropdown',
    label: 'Months',
    key: 'paymentMonths',
    required: true,
    visible: true,
    order: 2,
    options: ['3', '4', '5', '6'],
  },
  {
    id: '3',
    type: 'text',
    label: 'Upfront Amount',
    key: 'upfrontAmount',
    required: true,
    visible: true,
    order: 3,
    placeholder: 'e.g. 500',
    validation: { pattern: '^\\d+(\\.\\d+)?$' },
  },
];

export const DEFAULT_CLIENT_INTAKE_FIELDS: FormField[] = [
  { id: '1', type: 'text', label: 'Salesperson', key: 'salesperson', required: true, visible: true, order: 1 },
  { id: '2', type: 'text', label: 'Ref', key: 'ref', required: true, visible: true, order: 2 },
  { id: '3', type: 'text', label: 'Area of Interest (Roles)', key: 'areaOfInterestRoles', required: true, visible: true, order: 3 },
  { id: '4', type: 'text', label: 'Full Name', key: 'fullName', required: true, visible: true, order: 4 },
  { id: '5', type: 'text', label: 'Date of Birth', key: 'dateOfBirth', required: true, visible: true, order: 5 },
  { id: '6', type: 'text', label: 'Visa Status', key: 'visaStatus', required: true, visible: true, order: 6 },
  { id: '7', type: 'text', label: 'Arrival in the USA', key: 'arrivalInUsa', required: true, visible: true, order: 7 },
  { id: '8', type: 'text', label: "Master’s Degree Details", key: 'mastersDegreeDetails', required: true, visible: true, order: 8 },
  { id: '9', type: 'text', label: "Bachelor’s Degree Details", key: 'bachelorsDegreeDetails', required: true, visible: true, order: 9 },
  { id: '10', type: 'email', label: 'Email Address', key: 'email', required: true, visible: true, order: 10 },
  { id: '11', type: 'phone', label: 'Contact Number', key: 'phone', required: true, visible: true, order: 11 },
  { id: '12', type: 'text', label: 'Current Location', key: 'currentLocation', required: true, visible: true, order: 12 },
  { id: '13', type: 'text', label: 'Total Experience', key: 'totalExperience', required: true, visible: true, order: 13 },
  { id: '14', type: 'textarea', label: 'Technology/Skill Set', key: 'technologySkillSet', required: true, visible: true, order: 14 },
  { id: '15', type: 'dropdown', label: 'Open to Relocation (Yes/No)', key: 'openToRelocation', required: true, visible: true, order: 15, options: ['Yes', 'No'] },
  { id: '16', type: 'text', label: 'Availability for Marketing', key: 'availabilityForMarketing', required: true, visible: true, order: 16 },
  { id: '17', type: 'text', label: 'Agreement', key: 'agreement', required: true, visible: true, order: 17 },
  // `upfront` is the field stored on the client's personal-details record.
  // The label reads "Upfront". The form auto-fills this with the value
  // of the lead's `amount` field on first render so the agent doesn't
  // have to retype it; the agent can override it before saving.
  { id: '18', type: 'text', label: 'Upfront', key: 'upfront', required: true, visible: true, order: 18 },
  { id: '19', type: 'text', label: 'BGC', key: 'bgc', required: true, visible: true, order: 19 },
  { id: '20', type: 'text', label: 'LinkedIn profile link', key: 'linkedinProfileUrl', required: true, visible: true, order: 20 },
];

function buildOptionKey(value: string, fieldKey?: string): string {
  const trimmed = value.trim().toLowerCase();
  if (fieldKey === 'status') {
    return trimmed.replace(/[\s_-]+/g, ' ').trim();
  }
  return trimmed;
}

function canonicalizeOption(value: string, fieldKey?: string): string {
  const trimmed = value.trim();
  if (fieldKey === 'status') {
    const key = buildOptionKey(trimmed, fieldKey);
    if (key === 'not interested') return 'Not Interested';
  }
  return trimmed;
}

function dedupeOptions(options: unknown, fieldKey?: string): string[] | undefined {
  if (!Array.isArray(options)) return undefined;
  const seen = new Set<string>();
  const result: string[] = [];
  for (const entry of options) {
    if (typeof entry !== 'string') continue;
    const normalized = entry.trim();
    if (!normalized) continue;
    const canonical = canonicalizeOption(normalized, fieldKey);
    const key = buildOptionKey(canonical, fieldKey);
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(canonical);
  }
  return result;
}

function normalizeFormFields(fields: FormField[]): FormField[] {
  return fields.map((field) => {
    if (field.type !== 'dropdown' && field.type !== 'checklist') return field;
    const options = dedupeOptions(field.options, field.key);
    return options ? { ...field, options } : { ...field, options: undefined };
  });
}

async function getFormConfigDocument(
  docId: string,
  defaultFields: FormField[]
): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  try {
    const config = await databases.getDocument(DATABASE_ID, FORM_CONFIG_COLLECTION_ID, docId);
    const fields = normalizeFormFields(JSON.parse(config.fields as string) as FormField[]);

    return {
      fields,
      version: config.version as number,
      updatedBy: config.updatedBy as string,
    };
  } catch (error: any) {
    if (error.code === 404 || error.message?.includes('not found')) {
      return {
        fields: normalizeFormFields(defaultFields),
        version: 0,
        updatedBy: '',
      };
    }

    console.error('Error fetching form config:', error);
    throw new Error(error.message || 'Failed to fetch form configuration');
  }
}

/**
 * Get the current form configuration
 *
 * This function fetches the form configuration from the database.
 * If no configuration exists, it returns the default fields.
 *
 * @returns The current form configuration with parsed fields
 */
export async function getFormConfig(): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  return getFormConfigDocument(FORM_CONFIG_DOC_ID, DEFAULT_FIELDS);
}

export async function getClosureFormConfig(): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  return getFormConfigDocument(CLOSURE_FORM_CONFIG_DOC_ID, DEFAULT_CLOSURE_FIELDS);
}

export async function getPaymentPlanFormConfig(): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  return getFormConfigDocument(PAYMENT_PLAN_FORM_CONFIG_DOC_ID, DEFAULT_PAYMENT_PLAN_FIELDS);
}

export async function getClientIntakeFormConfig(): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  return getFormConfigDocument(CLIENT_INTAKE_FORM_CONFIG_DOC_ID, DEFAULT_CLIENT_INTAKE_FIELDS);
}

/**
 * Calculate the difference between old and new field configurations
 */
function calculateFieldDiff(oldFields: FormField[], newFields: FormField[]) {
  const added: FormField[] = [];
  const removed: FormField[] = [];
  const modified: { key: string; label: string; changes: any }[] = [];

  const oldMap = new Map(oldFields.map(f => [f.key, f]));
  const newMap = new Map(newFields.map(f => [f.key, f]));

  // Find added and modified fields
  for (const newField of newFields) {
    const oldField = oldMap.get(newField.key);
    if (!oldField) {
      added.push(newField);
    } else {
      const changes: any = {};
      let hasChanges = false;

      // Check specific properties
      if (oldField.label !== newField.label) {
        changes.label = { from: oldField.label, to: newField.label };
        hasChanges = true;
      }
      if (oldField.required !== newField.required) {
        changes.required = { from: oldField.required, to: newField.required };
        hasChanges = true;
      }
      if (oldField.visible !== newField.visible) {
        changes.visible = { from: oldField.visible, to: newField.visible };
        hasChanges = true;
      }
      if (oldField.order !== newField.order) {
        changes.order = { from: oldField.order, to: newField.order };
        hasChanges = true;
      }
      if (JSON.stringify(oldField.options) !== JSON.stringify(newField.options)) {
        changes.options = { from: oldField.options, to: newField.options };
        hasChanges = true;
      }

      if (hasChanges) {
        modified.push({
          key: newField.key,
          label: newField.label,
          changes
        });
      }
    }
  }

  // Find removed fields
  for (const oldField of oldFields) {
    if (!newMap.has(oldField.key)) {
      removed.push(oldField);
    }
  }

  return { added, removed, modified };
}

/**
 * Update the form configuration
 *
 * This function updates the form configuration with new fields.
 * It automatically increments the version number and uses the singleton pattern.
 *
 * @param fields - The new form fields configuration
 * @param actorId - The ID of the actor making the update
 * @param actorName - The name of the actor (optional, for logging)
 * @returns The updated form configuration
 */
export async function updateFormConfig(
  fields: FormField[],
  actorId: string,
  actorName?: string
): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  void fields;
  void actorId;
  void actorName;
  throw new Error('Field management is disabled');
  }

/**
 * Add a new field to the form configuration
 *
 * @param field - The field to add
 * @param actorId - The ID of the actor making the update
 * @param actorName - The name of the actor (optional, for logging)
 * @returns The updated form configuration
 */
export async function addField(
  field: FormField,
  actorId: string,
  actorName?: string
): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  const currentConfig = await getFormConfig();
  const fields = [...currentConfig.fields, field];
  return updateFormConfig(fields, actorId, actorName);
}

/**
 * Remove a field from the form configuration
 *
 * @param fieldId - The ID of the field to remove
 * @param actorId - The ID of the actor making the update
 * @param actorName - The name of the actor (optional, for logging)
 * @returns The updated form configuration
 */
export async function removeField(
  fieldId: string,
  actorId: string,
  actorName?: string
): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  const currentConfig = await getFormConfig();
  const fields = currentConfig.fields.filter((f) => f.id !== fieldId);

  // Reorder remaining fields to maintain sequential order
  const reorderedFields = fields.map((field, index) => ({
    ...field,
    order: index + 1,
  }));

  return updateFormConfig(reorderedFields, actorId, actorName);
}

/**
 * Reorder fields in the form configuration
 *
 * @param fieldIds - Array of field IDs in the desired order
 * @param actorId - The ID of the actor making the update
 * @returns The updated form configuration
 */
export async function reorderFields(fieldIds: string[], actorId: string): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  const currentConfig = await getFormConfig();

  // Create a map of field ID to field for quick lookup
  const fieldMap = new Map(currentConfig.fields.map((f) => [f.id, f]));

  // Reorder fields based on the provided IDs and update order property
  const reorderedFields = fieldIds
    .map((id) => fieldMap.get(id))
    .filter((field): field is FormField => field !== undefined)
    .map((field, index) => ({
      ...field,
      order: index + 1,
    }));

  return updateFormConfig(reorderedFields, actorId);
}

/**
 * Update a specific field in the form configuration
 *
 * @param fieldId - The ID of the field to update
 * @param updates - Partial field updates
 * @param actorId - The ID of the actor making the update
 * @param actorName - The name of the actor (optional, for logging)
 * @returns The updated form configuration
 */
export async function updateField(
  fieldId: string,
  updates: Partial<FormField>,
  actorId: string,
  actorName?: string
): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  const currentConfig = await getFormConfig();
  const fields = currentConfig.fields.map((field) =>
    field.id === fieldId ? { ...field, ...updates } : field
  );

  return updateFormConfig(fields, actorId, actorName);
}

/**
 * Toggle field visibility
 *
 * @param fieldId - The ID of the field to toggle
 * @param actorId - The ID of the actor making the update
 * @param actorName - The name of the actor (optional, for logging)
 * @returns The updated form configuration
 */
export async function toggleFieldVisibility(
  fieldId: string,
  actorId: string,
  actorName?: string
): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  const currentConfig = await getFormConfig();
  const field = currentConfig.fields.find((f) => f.id === fieldId);

  if (!field) {
    throw new Error('Field not found');
  }

  return updateField(fieldId, { visible: !field.visible }, actorId, actorName);
}

/**
 * Toggle field required status
 *
 * @param fieldId - The ID of the field to toggle
 * @param actorId - The ID of the actor making the update
 * @param actorName - The name of the actor (optional, for logging)
 * @returns The updated form configuration
 */
export async function toggleFieldRequired(
  fieldId: string,
  actorId: string,
  actorName?: string
): Promise<{ fields: FormField[]; version: number; updatedBy: string }> {
  const currentConfig = await getFormConfig();
  const field = currentConfig.fields.find((f) => f.id === fieldId);

  if (!field) {
    throw new Error('Field not found');
  }

  return updateField(fieldId, { required: !field.required }, actorId, actorName);
}
