import type { ComponentType } from 'react';
import {
  Briefcase,
  Building2,
  ChartColumn,
  ClipboardCheck,
  ClipboardList,
  Bell,
  CalendarClock,
  FileSpreadsheet,
  FileText,
  FormInput,
  LayoutDashboard,
  Link2,
  Mail,
  MessageSquare,
  Network,
  NotebookTabs,
  PhoneCall,
  ShieldCheck,
  Settings,
  Target,
  TrendingUp,
  UserCog,
  Users,
  Video,
  Wallet,
} from 'lucide-react';

export type AppIcon = ComponentType<{ className?: string; size?: number }>;

export interface NavItem {
  key: string;
  label: string;
  href: string;
  icon: AppIcon;
}

export const appIcons = {
  dashboard: LayoutDashboard,
  branches: Building2,
  leads: FileText,
  clients: Briefcase,
  mock: Mail,
  assessmentSupport: ClipboardCheck,
  interviewSupport: Video,
  hierarchy: Network,
  users: Users,
  fieldManagement: FormInput,
  auditLogs: ClipboardList,
  workQueue: CalendarClock,
  reports: TrendingUp,
  coachingNotes: NotebookTabs,
  reviewQueue: ShieldCheck,
  notifications: Bell,
  attendance: CalendarClock,
  attendanceReport: ClipboardList,
  chat: MessageSquare,
  settings: Settings,
  linkedinRequests: Link2,
  linkedinAccounts: UserCog,
  linkedinReports: ChartColumn,
  leadRequests: ClipboardList,
  paymentsReport: Wallet,
  targetReport: Target,
  technicalPayments: Wallet,
  followupsPayments: Wallet,
  resumeDashboard: FileSpreadsheet,
  resumeHierarchy: Network,
  requestCalls: PhoneCall,
  callRequests: PhoneCall,
  resumeProfiles: FileText,
  resumeMarketing: TrendingUp,
  assignedReport: ClipboardCheck,
} satisfies Record<string, AppIcon>;

export const NAV_ITEMS: NavItem[] = [
  { key: 'dashboard', label: 'Dashboard', href: '/dashboard', icon: appIcons.dashboard },
  { key: 'attendance', label: 'Attendance', href: '/attendance', icon: appIcons.attendance },
  { key: 'attendance-report', label: 'Attendance Report', href: '/attendance-report', icon: appIcons.attendanceReport },
  { key: 'chat', label: 'Chatting', href: '/chat/announcement', icon: appIcons.chat },
  { key: 'resume-chat', label: 'Resume Chat', href: '/resume-chat/announcement', icon: appIcons.chat },
  { key: 'branch-management', label: 'Branches', href: '/branches', icon: appIcons.branches },
  { key: 'leads', label: 'Leads', href: '/leads', icon: appIcons.leads },
  { key: 'lead-requests', label: 'Lead Requests', href: '/lead-requests', icon: appIcons.leadRequests },
  { key: 'history', label: 'Client', href: '/client', icon: appIcons.clients },
  { key: 'request-calls', label: 'Request Calls', href: '/request-calls', icon: appIcons.requestCalls },
  { key: 'work-queue', label: 'Work Queue', href: '/work-queue', icon: appIcons.workQueue },
  { key: 'reports', label: 'Reports', href: '/reports', icon: appIcons.reports },
  { key: 'coaching-notes', label: 'Coaching Notes', href: '/coaching-notes', icon: appIcons.coachingNotes },
  { key: 'review-queue', label: 'Review Queue', href: '/review-queue', icon: appIcons.reviewQueue },
  { key: 'linkedin-requests', label: 'Linkedin Request', href: '/linkedin-requests', icon: appIcons.linkedinRequests },
  { key: 'linkedin-account-management', label: 'Manage Linkedin IDs', href: '/linkedin-accounts', icon: appIcons.linkedinAccounts },
  { key: 'linkedin-reports', label: 'Linkedin Reports', href: '/linkedin-reports', icon: appIcons.linkedinReports },
  { key: 'payments-report', label: 'Payments Report', href: '/payments-report', icon: appIcons.paymentsReport },
  { key: 'target-report', label: 'Target Report', href: '/target-report', icon: appIcons.targetReport },
  { key: 'technical-payments', label: 'Technical Payments', href: '/technical-payments', icon: appIcons.technicalPayments },
  { key: 'followups-payments', label: 'Followups Payments', href: '/previous-followups-payments', icon: appIcons.followupsPayments },
  { key: 'resume-dashboard', label: 'Resume Dashboard', href: '/resume-dashboard', icon: appIcons.resumeDashboard },
  { key: 'call-requests', label: 'Calls', href: '/call-requests', icon: appIcons.callRequests },
  { key: 'resume-profiles', label: 'Resume Profiles', href: '/resume', icon: appIcons.resumeProfiles },
  { key: 'resume-marketing', label: 'Marketing', href: '/resume-marketing', icon: appIcons.resumeMarketing },
  { key: 'resume-hierarchy', label: 'Resume Hierarchy', href: '/resume-hierarchy', icon: appIcons.resumeHierarchy },
  { key: 'mock', label: 'Mock Interview', href: '/mock', icon: appIcons.mock },
  { key: 'assessment-support', label: 'Assessment Support', href: '/assessment-support', icon: appIcons.assessmentSupport },
  { key: 'interview-support', label: 'Interview Support', href: '/interview-support', icon: appIcons.interviewSupport },
  { key: 'hierarchy', label: 'Hierarchy', href: '/hierarchy', icon: appIcons.hierarchy },
  { key: 'user-management', label: 'Users', href: '/users', icon: appIcons.users },
  { key: 'audit-logs', label: 'Audit Logs', href: '/audit-logs', icon: appIcons.auditLogs },
  { key: 'settings', label: 'Settings', href: '/settings', icon: appIcons.settings },
  { key: 'assigned-report', label: 'Assigned Report', href: '/assigned-report', icon: appIcons.assignedReport },
];
